apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-microservice
  template:
    metadata:
      labels:
        app: tickets-microservice
    spec:
      containers:
      - name: tickets-microservice
        image: provenzale/tickets-ms:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-microservice-service
spec:
  type: LoadBalancer
  selector:
    app: tickets-microservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000